tailwind.config.js

- Tailwind.config.js 커스텀 색상 수정하였습니다.

Chore: tailwind.config.js 커스텀 색상 수정

---

src/pages/Login.tsx

로그인 페이지 레이아웃 구현 (oAuth 제외) 했습니다.
- 로그인 페이지 레이아웃 구현
- oAuth svg 컴포넌트화 에러 문제로 이후  처리 예정입니다.

Style: 로그인 페이지 레이아웃 구현(oAuth 제외)

---

src/pages/Login.tsx
src/pages/Signup.tsx

회원가입 페이지 레이아웃 구현(스크립트 필요 부분 제외) 했습니다.
- 회원가입 페이지 레이아웃 구현
- 회원가입 페이지에서 퍼센트 바, 사진 업로드 미리보기는 스크립트 처리가 필요해서 이후 구현 예정입니다.

Style: 회원가입 페이지 레이아웃 구현(스크립트 필요 부분 제외)

---

package-lock.json
package.json
src/components/DarkToggle.tsx
src/components/Footer.tsx

Footer 레이아웃 생성 PR
- Footer 레이아웃 생성
- 팀원 깃허브 링크 연결 
- react-router-dom 설치하였습니다. dev pull 받으실 때 npm i 한번씩 해주세요.

Style: Footer 레이아웃 생성

---

src/components/DarkToggle.tsx

Style: 다크모드 토글 타입에 따라 return 값 변경

---

src/assets/svg/ArrowLeft.tsx
src/assets/svg/ArrowRight.tsx
src/components/Pagenation.tsx
src/components/button/Button.tsx
src/index.css
src/pages/Forum.tsx

재사용 페이지네이션 컴포넌트 UI 구현
재사용 버튼 컴포넌트 생성 
[재사용] 페이지네이션 컴포넌트 구현 > components>Pagenation.tsx
[재사용] 버튼 컴포넌트 구현 > components>button>Button.tsx
- index.css에 공통으로 사용할 수 있는 tailwindCSs className 생성
```javaScript 
@tailwind base;
@tailwind components;
@tailwind utilities;
@layer components {
.blue_squareBtn {
@apply py-2 px-5 text-center bg-MAIN_COLOR text-BASIC_WHITE hover:bg-BTN_HOVER_COLOR rounded-lg font-medium;
}
.blue_circleBtn {
@apply py-2 px-5 bg-MAIN_COLOR text-BASIC_WHITE hover:bg-BTN_HOVER_COLOR rounded-3xl font-medium;
}
}
```
- 사용할 컴포넌트에 Button 컴포넌트 imort 
- 원하는 타입과 추가 커스터마이징 할 높이나 색상을 적용하여 props로 넘겨줌
```javaScript 
const Forum = () => {
const btnInfo: btnAttributes = {
width: "172px",
height: "50px",
text: "새 글 등록하기",
type: "circle",
};
//생략
<Button btnInfo={btnInfo} />
```

Style: 재사용 페이지네이션 + 버튼 컴포넌트 생성

---

src/common/button/Button.tsx
src/components/modal/BasicModal.tsx
src/components/modal/MypageModal.tsx
src/components/modal/PwdModal.tsx
src/pages/Forum.tsx
src/types/toggle.ts

재사용 모달 컴포넌트 생성 PR
- 재사용 모달 알림 컴포넌트 : BasicModal.tsx
- 비밀번호 변경 모달 컴포넌트 : PwdModal.tsx
- 프로필 수정 모달 컴포넌트 : MypageModal.tsx

Style: 재사용 모달 컴포넌트 생성

---

src/components/modal/MypageModal.tsx
src/components/modal/PwdModal.tsx
src/components/mypage/EditProfile.tsx

공용 모달 컴포넌트 수정
- 공용 모달 컴포넌트(비밀번호 변경, 프로필 수정 ) 의 margin, padding 값 수정
- 버튼 추가
- 버튼 위치 조정 안됨

Style: 공용 모달 컴포넌트 수정:

---

src/common/button/Button.tsx
src/pages/EditForum.tsx

여행 후기 수정 및 등록 페이지 생성 PR
- 여행 후기 수정 및 등록 페이지 생성
- 버튼 컴포넌트에 글자 색성 속성 추가 
- 에디터 라이브러리 미 적용 상태

Style: 여행 후기 수정및 등록 페이지 생성

---

src/common/category/Category.tsx
src/components/forumItems/ForumItem.tsx
src/pages/DetailForum.tsx

카테고리 컴포넌트 별도로 생성하여 재사용할 수 있게 하였음.
- common 폴더에 Category 컴포넌트 생성하여 입력 값에 따라 "에디터 추천 " 과 "여행후기" 카테고리로 변동 되도록 설정.

Style: 카테고리 컴포넌트 별도로 생성

---

src/assets/svg/Bell.tsx
src/components/mineItems/LikeItem.tsx
src/components/mineItems/WroteComment.tsx
src/components/mineItems/WroteForum.tsx
src/components/mypage/Mine.tsx
src/pages/Mypage.tsx

마이페이지 보관함에 들어갈 아이템 컴포넌트 생성 
- 내가 쓴 게시글 보관 아이템
- 내가 댓글 단 게시글 보관 아이템 
- 내가 좋아요 한 상품 보관 아이템

Style: 마이페이지 보관함에 사용할 아이템 생성

---

tailwind.config.js

tailwind.config.js에 dark-gray-color 색상 추가

Chore: tailwind.config.js 색상 추가

---

src/components/header/Header.tsx
src/components/header/Topnav.tsx
src/components/productCardItems/ProductCardItems.tsx
src/components/recommendProductItems/RecommendProductItems.tsx
src/components/regionProductTheme/RegionProductTheme.tsx
src/components/search/Search.tsx
src/pages/Home.tsx
src/pages/ProductList.tsx
src/pages/ProductListDetail.tsx

페이지별 전체 레이아웃 수정
- 홈
- 상품 목록
- 상품 상세
- 헤더
- 검색 컴포넌트
- 게시글 목록
- 게시글 상세
- 마이페이지

Style: 페이지 별 전체 레이아웃 수정

---

src/pages/DetailForum.tsx
src/pages/Forum.tsx

여행 포럼 목록, 상세 페이지 전체 레이아웃 1차 수정

Style: 여행 포럼 전체 레이아웃 1차 수정

---

package-lock.json
package.json
src/App.tsx
src/components/Test.tsx
src/components/TextEditor.tsx
src/pages/EditForum.tsx
vite.config.ts

간단한 aPI 통신을 테스트 할 수 있도록 테스트 페이지 구현 
- /test : 테스트할 수 있는 페이지 입니다. 
- 간단한 axios 로 구현해두었습니다.

Feat: Proxy 테스트  구현

---

package-lock.json
package.json
src/components/TextEditor.tsx
src/pages/EditForum.tsx

여행 포럼 수정 페이지의 텍스트 에디터  ckEditor5 Classic 으로 구현 
- 사진 등록 안됨 -> 이미지 업로드 서버 필요하기 때문 
- 별도의 imageUploadAdapter 설치 필요. 
- 로컬에서 사진 등록 시 서버로 보내는 요청 필요

Feat: 여행포럼 수정 페이지의 텍스트 에디터 Classic 설정

---

src/components/signup/SignupInput.tsx
src/pages/Signup.tsx

회원가입 페이지 1차 기능 구현
- 인풋창 onchange 이벤트 적용
- 인풋창 value state 관리
- 인풋창 -> 컴포넌트 분리
- 상단 퍼센트 바 style 적용
- 프로필 이미지 업로드시 미리보기 이미지 적용
- 비밀번호, 비밀번호 확인 유효성 검사 구현
- 통신 시도 시 실제 회원가입 post 요청 구현 예정

Feat: 회원가입 페이지 1차 기능 구현

---

src/pages/Signup.tsx

Signup.tsx 파일의 useEffect 의 의존성 부분의 esLint 경고 무시하기 위핸 주석 설정

Comment: Signup 페이지의 useEffect 의존성 eslint 무시 설정

---

src/components/Layout.tsx
src/index.css
src/pages/DetailForum.tsx
src/pages/EditForum.tsx
src/pages/Forum.tsx
src/pages/Home.tsx
src/pages/Login.tsx
src/pages/Mypage.tsx
src/pages/Signup.tsx

전역 페이지에 Layout 컴포넌트로 관리할 수 있도록 작업 설정
- 전체 페이지 최상단 div에 w-full 적용
- Layout.tsx로 전체 레이아웃 관리  
- 데스크톱 사이즈일 경우 양 여백 생성 
- 모바일, 태블릿 사이즈 w-full 사이즈 적용

Style: 전역 페이지 Layout 설정

---

src/pages/Login.tsx

로그인 페이지 Input onChange 이벤트 추가
- 로그인 페이지 이메일, 비밀번호 onChange 이벤트 추가하였습니다.

Feat: 로그인 페이지 Input onchange 추가

---

src/pages/Login.tsx
src/pages/ProductListDetail.tsx

교통편에서 날짜 선택 시 해당 날짜 보이도록 기능 구현
- 교통편 날짜 -> 기본값으로 오늘 날짜, 선택한 날짜가 있다면 바뀌도록 구현했습니다.

Feat: 날짜 선택 시 해당 날짜 보여주기 구현

---

src/pages/Signup.tsx

의존성 배열 변수 수정
- 의존성 배열 에러로 변수로 빼어 수정하였습니다. (에러 재 발생시 말씀 부탁드립니다. 제쪽에서는 안 보이네요 ㅠㅠ )

Style: 의존성 배열 변수 수정

---

src/components/Bookmark/Bookmark.tsx
src/components/productListItems/ProductListItems.tsx
src/components/recommendProductItems/RecommendProductItems.tsx
src/components/regionProductTheme/RegionProductTheme.tsx
src/pages/Home.tsx
src/pages/ProductList.tsx

홈, 상품 목록 페이지 반응형 작업
- 홈 반응형 작업 
- 상품 목록 페이지 반응형 작업
- 상품 목록 페이지 반응형 작업 미완성 상태입니다. (로그인 axios 시도 후 재구현 예정)

Style: 홈, 상품 목록 페이지 반응형 작업

---

src/components/Test.tsx

Style: api 테스트 파일 수정

---

.env

.env 전역에 BASE _URL 환경 변수 설정 
**const BASE_URL = import.meta.env.VITE_BASE_URL;**   로 접근 할 수 있습니다.

Chore: env BASE URL 설정

---

src/components/Bookmark/Bookmark.tsx
src/components/Footer.tsx
src/components/header/Header.tsx
src/components/header/Mmenu.tsx
src/components/header/Topnav.tsx
src/components/productListItems/ProductListItems.tsx
src/components/search/Search.tsx
src/pages/ProductList.tsx
src/pages/ProductListDetail.tsx
src/pages/Signup.tsx

반응형 레이아웃 작업
- 홈 페이지 반응형
- 상품 목록 페이지 반응형
- 상품 상세 페이지 반응형
- 푸터 반응형
- 헤더 모바일 버전 z-index 및 함수 수정
-> 미리보기 파일이 너무 늘어날 것으로 생각되어 상단부분만 캡쳐

Style: 반응형 레이아웃 작업

---

src/pages/Forum.tsx

Forum 페이지(페이지네이션) 주석 처리 
아직 데이터 형태 정립되지 않아 에러 방지를 위해 주석 처리

Comment: Forum 페이지 주석 처리

---

src/pages/Signup.tsx

이메일 인증 및 회원가입 Post 요청 기능 구현
- 이메일 인증 구현 -> 적합한 이메일 입력 후 버튼 클릭 시 해당 이메일로 메일 전송. 메일에 있는 링크 클릭해야 이메일 확인해야 합니다.
- 회원가입 post 요청 기능구현 -> 요청 시 500번 코드 뜨는 것 확인하였습니다. 이후 처리 예정입니다.
- 이메일 인증은 링크 클릭을 해야한다는 안내 필요합니다.
- 회원가입 처리는 서버 측 보완 이후 재 시도 예정입니다.

Feat: 이메일 인증 및 회원가입 post 요청 기능 구현

---

.env
.gitignore
src/App.tsx
src/components/OauthRedirect/KakaoRedirect.tsx
src/pages/Login.tsx

로그인 기능 구현
- 로그인 기능 구현했습니다. (이메일, 비밀번호 입력 후 로그인 -> 통신 200 코드 확인)
- 소셜로그인 (카카오) 인가코드 받아오는 작업 확인하였습니다. 이후 추가 수정 예정입니다.
- gitignore(수정), .env(삭제) 하였습니다.

Feat: 로그인 기능 구현

---

src/pages/Signup.tsx

회원가입 기능 구현
- 회원가입 기능 구현(통신 200코드 확인) 하였습니다.

Feat: 회원가입 기능 구현

---

src/pages/FindPw.tsx
src/pages/Login.tsx

비밀번호 찾기 기능 구현 및 액세스 토큰 로컬스토리지 저장 구현
- 로그인 시 받은 액세스 토큰 로컬스토리지 저장했습니다.
- 비밀번호 찾기 기능 구현했습니다. (새로운 페이지로 이동하여 해당 페이지에서 이메일 작성 후 post 요청)

Feat: 비밀번호 찾기 기능 구현

---

src/App.tsx

App.js Route 추가(카카오 로그인, 비밀번호 찾기 -> 컴포넌트와 페이지로 따로 분리하여서 연결짓는 작업)

Style: 카카오 로그인, 비밀번호 찾기 루트 추가

---

src/assets/svg/Close.tsx
src/assets/svg/Hamburger.tsx
src/components/Footer.tsx
src/components/header/DarkToggle.tsx
src/components/header/Header.tsx
src/components/header/Mmenu.tsx
src/components/header/Topnav.tsx
src/components/productListItems/ProductListItems.tsx
src/index.css
src/pages/Home.tsx
src/pages/ProductList.tsx
src/pages/ProductListDetail.tsx
tailwind.config.js

다크모드 1차 구현
- 홈
- 헤더
- 푸터
- 상품 목록
- 상품 상세
위의 페이지는 다크 모드를 구현하였습니다.
svg 파일의 경우 조건부 스타일링 적용 시 즉각 적용되지 않습니다.
해당 부분 보완하도록 하겠습니다.

Style: 다크모드 1차 구현

---

src/pages/Login.tsx

소셜로그인 코드 수정, useMutation 적용
- 소셜로그인 비동기 요청 코드 -> a태그 href로 변경하였습니다.
- 로그인 Post 요청 코드 useMutation 적용하였습니다.

Style: 소셜로그인 코드 수정, useMutation 적용

---

src/pages/Signup.tsx

이메일 인증, 회원가입 react-query 적용
- 이메일 인증과 회원가입 api 요청 코드에 리액트 쿼리 훅인 useMutation 적용하였습니다.

Style: 이메일 인증, 회원가입 react-query 적용

---

src/components/header/DarkToggle.tsx

다크모드 토글 로컬스토리지 theme 에 따른 상태 수정
- 브라우저 종료 시(라이트모드 변경X) 다크모드 토글은 라이트모드로 바뀌어서 해당 부분 수정했습니다.

Style: 다크모드 토글 로컬스토리지 theme 에 따른 상태 수정

---

package-lock.json
package.json
postcss.config.js
src/App.tsx
src/ckeditor.ts
src/common/button/AmendBtn.tsx
src/common/button/DeleteBtn.tsx
src/common/category/Category.tsx
src/components/Pagenation.tsx
src/components/TextEditor.tsx
src/components/comment/Comment.tsx
src/components/comment/CommentItem.tsx
src/components/comment/EditComment.tsx
src/components/comment/HideComment.tsx
src/components/forumItems/ForumItem.tsx
src/components/modal/PwdModal.tsx
src/components/mypage/EditProfile.tsx
src/index.css
src/pages/DetailForum.tsx
src/pages/EditForum.tsx
src/pages/Forum.tsx
src/pages/Mypage.tsx
tailwind.config.js
vite.config.ts

게시글 상세 페이지 및 전체 조회 페이지 관련 기능 구현 
- 전체 목록 데이터 확인 
- 댓글 수정, 삭제, 등록 가능 
- 게시글 등록 및 조회 가능 (수정 미 구현)
- 다크모드 배경 및 텍스트 색상 적용
- 페이지 목록 부분의 반응형 글자 사이즈 조정 중 
- ckeditor5 타입 문제 
- 댓글 보기 클릭 시 전체 클릭 되는 문제 발생

Feat: 게시글 상세 페이지 및 전체 조회 페이지 관련 기능 구현 

---

src/components/comment/CommentItem.tsx
src/hooks/useFormatDate.tsx
src/hooks/useFormatTitle.tsx
src/pages/DetailForum.tsx

제목 텍스트 길이 제한 hook 및 날짜 포맷 변환 hook 생성 및 적용

Feat: 제목 텍스트 길이 제한 hook 및 날짜 포맷 변환 hook 생성 및 적용 

---

src/pages/Forum.tsx

포럼 메인 목록 페이지에서 상세 페이지로 링크 이동 연결

Feat: 포럼 메인 목록 페이지에서 상세 페이지로 링크 이동 연결

---

src/components/TextEditor.tsx
src/pages/DetailForum.tsx
src/pages/EditForum.tsx

게시글 수정 기능 테스트 완료 
- 게시글 등록 
- 게시글 수정
- 게시글 삭제

Feat: 게시글 수정 기능 테스트 완료

---

src/pages/ProductListDetail.tsx
vite.config.ts

고속버스 api 기능 1차구현 시도
- 티머니 고속버스 api 기능 구현 1차 시도하였습니다.
- Open api cors 문제로 프록시 설정하였습니다.
- 데이터 가공후 렌더링하는 작업 예정입니다.

Style: 고속버스 api 기능 1차구현 시도

---

src/pages/Signup.tsx

회원가입 api 요청 코드 수정
- 회원가입 프로필 이미지 formdata 키 이름 변경하였습니다.

Style: 회원가입 api 요청 코드 수정

---

README.md

Docs: Readme 1차 작성

---

src/components/searchVehicle/SearchVehicle.tsx
src/pages/ProductListDetail.tsx
vite.config.ts

교통편 검색 1차 기능 구현
- 버스 노선 검색 기능 구현했습니다. (터미널명, 시간, 일자 적용 후 검색 클릭 시 정보 조회 가능)
- 해당 교통편 검색 부분 컴포넌트로 분리하였습니다.
상품 상세 교통편 컴포넌트에서 의존성 배열 워닝 뜨는데 이후에 처리하겠습니다.
교통편 출발지, 도착치 드롭다운 디자인 구현할 예정입니다.
조회되는 배차리스트가 있을 시 해당 레이아웃도 구현 예정입니다.

Feat: 교통편 검색 1차 기능 구현

---

src/components/search/Search.tsx
src/pages/Forum.tsx

포럼 페이지 검색 기능 구현 
- 검색 창에 키워드 입력 후 "Enter" 키 작동 시 검색 된 데이터 조회 가능 
- 태그 # 키워드 검색은 아직 구현 안함.

Feat: 포럼 페이지 검색 기능 구현

---

src/components/forumItems/ForumItem.tsx
src/pages/Forum.tsx

여행 포럼 페이지의 필터링 기능 추가
- 인기 높은 순, 인기 낮은 순 , 최신 순 필터링 기능 구현 
* 좋아요 기능 구현되어 있지 않아서 현재 모든 데이터 동일 
- 카테고리 에디터 , 일반 유저 필터링 기능 구현 
* 요청 url 정확하게 어떻게 보내져야 하는지 확인 후 코드 수정 필요 
* 현재 삼항 연산자로 좋아요에 따른 필터링만 나누어져있다.

Feat: 여행 포럼 페이지의 필터링 기능 추가

---

src/components/comment/Comment.tsx
src/components/comment/CommentItem.tsx
src/components/lexical/plugins/ImagePlugin.tsx
src/pages/Forum.tsx
src/pages/Login.tsx

댓글 컴포넌트에 유저 이미지 적용
- 댓글 부분에 작성자 유저 이미지 적용

Feat: 댓글 컴포넌트에 유저 이미지 적용

---

src/pages/Login.tsx
src/pages/Signup.tsx

Feat: 로그인, 회원가입 성공시 navigate 구현

---

src/components/searchVehicle/SearchVehicle.tsx
vite.config.ts

교통편 조회 기능 구현 및 렌더링
- 교통편 조회 기능 구현하였습니다.
- vite-config 프록시 설정하였습니다.(티머니)
- 출발, 도착 드롭다운 구현 중입니다.

Feat: 교통편 조회 기능 구현 및 렌더링

---

src/components/lexical/plugins/ImagePlugin.tsx
src/components/lexical/plugins/ToolbarPlugin.tsx
src/components/lexical/ui/LexDropdown.tsx

이미지 S3 연결해서 에디터 적용(BASE64제거)
- 이미지 로컬에서 가져올 때 서버랑 통신해서 S3 url 로 저장.

Feat: 이미지 S3 연결해서 에디터 적용(BASE64제거)

---

src/common/button/Button.tsx
src/components/comment/Comment.tsx
src/components/comment/EditComment.tsx
src/components/lexical/ReadLexical.tsx
src/pages/Forum.tsx

불필요한 console.log 주석 처리 및 포럼 필터링 인식 에러 해결\
- 포럼 필터링 최신순 필터링 인식하지 않는 에러 해결 
- 최신순은 무조건 기본 데이터 조회로 요청하도록 수정 (sorCode 제거)
- comment부분에서 불필요한 console.log 주석 처리

Fix: 불필요한 console.log 주석 처리 및 포럼 필터링 인식 에러 해결

---

src/pages/ProductList.tsx

Fix: ProducList 파일 배포 에러 수정

---

src/pages/Forum.tsx

Err: 포럼 페이지 length 인식 불가 배포 수정 작업

Err: 포럼 페이지 length 인식 불가 배포 수정 작업 

---

src/components/searchVehicle/SearchVehicle.tsx

Style: 티머니  프록시 해제

---

src/components/searchVehicle/SearchVehicle.tsx
src/pages/ProductList.tsx

 티머니 프록시 해제

---

netlify.toml

Chore: netlify toml 설정

---

netlify.toml
src/components/searchVehicle/SearchVehicle.tsx

 netlify toml 설정

---

netlify.toml
src/components/searchVehicle/SearchVehicle.tsx

Style: netlify 배포용 수정

---

src/components/Bookmark/Bookmark.tsx
src/store/bookmarkState.ts

Feat: bookmark recoil 설정

---

src/App.tsx
src/assets/svg/BackToList.tsx
src/components/productListItems/ProductListItems.tsx
src/components/searchVehicle/SearchVehicle.tsx
src/pages/ProductList.tsx
src/pages/ProductListDetail.tsx

- 상품 목록, 상품 디테일 조회 기능 구현
- 교통편 리액트 쿼리 적용

Feat: 상품 목록, 상품 디테일 조회 기능 구현

---

src/components/mypage/ProfileNav.tsx
src/types/myProfile.ts

Fix: 마이페이지 왼쪽 Nav 타입 import 수정

---

src/components/productListItems/ProductListItems.tsx

상품 이미지 추가
- 상품 목록 페이지에서의 상품 이미지 추가하였습니다. (상품 개별 아이템 컴포넌트에서 관리)

Style: 상품 이미지 추가

---

src/assets/svg/Upload.tsx
src/components/modal/MypageModal.tsx
src/components/mypage/EditProfile.tsx
src/pages/Mypage.tsx

마이페이지 수정 기능 구현
- 프로필 이미지, 자기소개, 닉네임 수정 가능 
- (태그는 아직 미 적용) 
- 마이페이지 업로드 이후 마이페이지 새로 업데이트 설정 해야 함

Feat: 마이페이지 수정 기능 구현

---

src/App.tsx

Feat: 전역에 sse 오픈 연결 설정

---

src/components/OauthRedirect/OauthRedirect.tsx

Style: 소셜로그인 액세스 토큰 저장 구현

---

src/App.tsx
src/components/notification/Notification.tsx

Comment: 실시간 알림 주석
- 실시간 알림 에러 발생으로 임시 주석 처리

Comment: 실시간 알림 주석

---

src/components/productListItems/ProductListItems.tsx
src/pages/ProductList.tsx
src/pages/ProductListDetail.tsx

상품 목록 페이지네이션 구현
- 상품 목록 데이터 페이지 네이션 구현했습니다.
페이지 6이후부터는 해당 페이지 파란색 글자색 처리 안되는 것 확인하였습니다.

Feat: 상품 목록 페이지네이션 구현

---

src/pages/Signup.tsx

Fix: 회원가입 프로필 이미지 에러 수정

---

src/components/Bookmark/Bookmark.tsx
src/store/bookmarkState.ts

Style: 북마크 코드 수정

---

src/App.tsx

Fix: App.tsx 실시간 알림 주석 처리

---

src/App.tsx
src/pages/Forum.tsx
src/pages/ProductList.tsx

Merge : 7.6차 dev-> main merge 코드 수정 작업

Merge : 7.6차 dev-> main merge 코드 수정 작업 

---

src/components/cardItems/HotBedge.tsx
src/components/cardItems/HotItem.tsx
src/pages/Forum.tsx

여행 포럼 페이지의 인기 상품 아이템 조회
- 여행 포럼 페이지에서 인기 상품 아이템 조회 (3개) 
- 반응형 작업 적용 (레이아웃 변경)

Feat: 여행 포럼 페이지의 인기 상품 아이템 조회

---

src/common/tag/RecoilTag.tsx
src/components/Loading/ErrState.tsx
src/components/modal/MypageModal.tsx
src/components/mypage/ProfileNav.tsx
src/pages/EditForum.tsx
src/pages/Mypage.tsx

마이페이지 태그 기능 구현 및 에러 페이지에서 토큰 만료 분기점 추가
- 마이페이지 관심 태그 기능 설정 기능 구현 
* 5개 이상 전달 불가 
* 0개 에러 발생 해결 
- 에러 컴포넌트에서 에러 메세지 401일 경우 로그인 페이지로 이동 기능 추가

Fix: 마이페이지 태그 기능 구현 및 에러 페이지에서 토큰 만료 분기점 추가

---

package-lock.json
src/components/home/HomeForum.tsx
src/components/productCardItems/ProductCardItems.tsx
src/components/recommendProductItems/RecommendProductItems.tsx
src/pages/Home.tsx
src/store/homeForumTagState.ts
src/store/tagState.ts

Feat: 메인 홈페이지 추천, 관련 상품 데이터 연결
- 메인 홈 페이지의 추천, 관련 상품 데이터 연결 작업 
- 상세 페이지로 링크 연결

Feat: 메인 홈페이지 추천, 관련 상품 데이터 연결

---

package-lock.json
package.json
src/assets/svg/Close.tsx
src/components/header/Header.tsx
src/components/notification/StoreNoti.tsx
src/components/productCardItems/ProductCardItems.tsx
src/pages/ProductListDetail.tsx

Feat: 알림 기능 구현 + 상품 상세 페이지 추천 상품 데이터 연결
- 알림 전체 삭제 
- 알림 일부 삭제 ( 에러 ) 
- 알림 읽음 처리 ( 미테스트 ) 
- 상품 상세 페이지에서 추천 상품 연결 
- 상품 상세 페이지에서 title로 태그 1개 끌어와서 대분류에 적용 
- 알림에는 Tag가 있는데 상세 페이지에는 태그 데이터가 없음

Feat: 알림 기능 구현 + 상품 상세 페이지 추천 상품 데이터 연결

---

src/components/Bookmark/Bookmark.tsx
src/components/productListItems/ProductListItems.tsx
src/pages/DetailForum.tsx
src/pages/ProductListDetail.tsx

Feat: 게시글 북마크 수정
- Bookmark에 타입 (게시글 , 아이템) 구분 자 추가하여 알맞은 body 속성 적용

Feat: 게시글 북마크 수정

---

src/components/Bookmark/Bookmark.tsx
src/components/cardItems/HotItem.tsx
src/components/search/Search.tsx
src/pages/Forum.tsx
src/pages/ProductList.tsx

Feat: 검색 컴포넌트 수정
- 이벤트 버블링 요소 제거 
- 태그 검색 수정
- 상품, 게시판 전체 검색 컴포넌트 리체크

Feat: 검색 컴포넌트 수정

---

package-lock.json
package.json
src/common/tag/RecoilTag.tsx
src/components/header/Mmenu.tsx
src/components/homeSlider/Slider2.tsx
src/components/mineItems/LikeItem.tsx
src/components/modal/MypageModal.tsx
src/pages/Home.tsx

Feat: 홈 슬라이더 에러 사항 해결 + 마이페이지 반응형 수정
- 홈 슬라이더 다른 페이지 이동 했다가 돌아왔을 때 에러나는 현상 해결 
* flowbite 미사용 -> 순수 React
- 마이페이지 반응형 수정 
* 좋아요 상품
* 이미지 
* 태그

Feat: 홈 슬라이더 에러 사항 해결 + 마이페이지 반응형 수정
